/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DrivingInterface */

#ifndef _Included_DrivingInterface
#define _Included_DrivingInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DrivingInterface
 * Method:    OpenSharedMemory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DrivingInterface_OpenSharedMemory
  (JNIEnv *, jobject);

/*
 * Class:     DrivingInterface
 * Method:    ReadSharedMemory
 * Signature: ([D[D[D[D[I[I[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_DrivingInterface_ReadSharedMemory
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     DrivingInterface
 * Method:    WriteSharedMemory
 * Signature: (DDDI)I
 */
JNIEXPORT jint JNICALL Java_DrivingInterface_WriteSharedMemory
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
